import * as dotenv from 'dotenv'

dotenv.config();

const {FRONTEND_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET} = process.env;

export {FRONTEND_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET};