import * as dotenv from 'dotenv'

dotenv.config();

const {API_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET, SECRET_COOKIE} = process.env;

export {API_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET, SECRET_COOKIE};