version: '3.9'

services:
  app:
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo

  dev:
    build: .
    command: "npm run dev:tsc"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
