import * as dotenv from 'dotenv'

dotenv.config();

const {REDIRECT_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET} = process.env;

export {REDIRECT_PORT, DATABASE_PORT, DATABASE_NAME, DATABASE_PASSWORD, SECRET};